"""Vulnerability Plugin Base Classes.

Design Principles:
1. Plugins ONLY generate payloads - they don't make vulnerability judgments
2. Plugins don't execute HTTP requests - Controller handles that
3. Plugins don't determine if vulnerabilities exist - AI Brain does that
4. Plugins only receive LLM judgment results and do post-processing
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from trix.models.finding import VulnFinding
from trix.models.judgment import JudgmentResult


@dataclass
class PayloadContext:
    """Context for payload generation.
    
    Provides all information a plugin needs to generate appropriate payloads.
    """
    target: str
    parameter: str
    method: str = "GET"
    original_value: str = ""
    content_type: str = ""
    
    # Additional context
    tech_stack: list[str] = field(default_factory=list)
    waf_detected: str | None = None
    custom_headers: dict[str, str] = field(default_factory=dict)


@dataclass
class PayloadSpec:
    """Specification for a single payload.
    
    Each payload includes metadata to help LLM understand what to look for.
    """
    payload: str
    description: str
    expected_behavior: str  # What would indicate vulnerability
    
    # Categorization
    category: str = ""  # e.g., "error-based", "time-based", "boolean-based"
    severity: str = "medium"  # Expected severity if successful
    
    # Detection hints for LLM
    success_patterns: list[str] = field(default_factory=list)
    failure_patterns: list[str] = field(default_factory=list)
    
    # Timing (for time-based detection)
    expected_delay_ms: int = 0


class BaseVulnPlugin(ABC):
    """Abstract base class for vulnerability detection plugins.
    
    Design Principles:
    1. Plugin ONLY generates payloads
    2. Plugin does NOT execute HTTP requests (Controller does that)
    3. Plugin does NOT judge vulnerabilities (AI Brain does that)
    4. Plugin only processes LLM judgment results
    
    Example:
        class SQLiPlugin(BaseVulnPlugin):
            name = "sqli_detector"
            vuln_type = "sqli"
            
            def generate_payloads(self, context):
                return [PayloadSpec(payload="'", description="Single quote", ...)]
    """
    
    # === Plugin Metadata (override in subclass) ===
    name: str = ""
    vuln_type: str = ""
    description: str = ""
    version: str = "1.0.0"
    author: str = ""
    
    # === Configuration ===
    enabled: bool = True
    max_payloads: int = 50
    use_ai_generation: bool = False  # Enable AI-driven bypass payload generation
    
    # === Abstract Methods ===
    
    @abstractmethod
    def generate_payloads(self, context: PayloadContext) -> list[PayloadSpec]:
        """Generate payloads for testing.
        
        This is the plugin's primary responsibility - creating test payloads.
        The plugin should NOT include any judgment logic.
        
        Args:
            context: PayloadContext with target, parameter, etc.
            
        Returns:
            List of PayloadSpec objects, each containing:
            - payload: The actual payload string
            - description: What this payload does
            - expected_behavior: What indicates success
        """
        pass
    
    async def generate_ai_payloads(
        self,
        context: PayloadContext,
        blocked_payload: str,
        raw_response: str,
        error_message: str = "",
        waf_type: str = "",
    ) -> list[PayloadSpec]:
        """Generate AI-driven bypass payloads when static payloads fail.
        
        Called when:
        1. Static payload was blocked (WAF/filter)
        2. AI confidence is in 30-50% range (suspects vuln but blocked)
        
        Args:
            context: Original payload context
            blocked_payload: The payload that was blocked
            raw_response: Response from the blocked request
            error_message: Specific error/block message if available
            waf_type: Detected WAF type if known
            
        Returns:
            List of AI-generated bypass PayloadSpec objects
        """
        if not self.use_ai_generation:
            return []
        
        try:
            from trix.plugins.smart_payload import (
                SmartPayloadGenerator,
                WAFAnalysisContext,
                get_smart_generator,
            )
            
            generator = get_smart_generator()
            
            waf_context = WAFAnalysisContext(
                vuln_type=self.vuln_type,
                original_payload=blocked_payload,
                raw_request="",  # Not always available at this level
                raw_response=raw_response,
                error_message=error_message,
                waf_detected=bool(waf_type or context.waf_detected),
                waf_type=waf_type or context.waf_detected or "",
            )
            
            return await generator.generate_bypass_payloads(waf_context, max_payloads=3)
            
        except Exception as e:
            import logging
            logging.getLogger(__name__).warning(f"AI payload generation failed: {e}")
            return []
    
    @abstractmethod
    def get_judgment_context(self, payload: PayloadSpec) -> dict[str, Any]:
        """Get additional context for LLM judgment.
        
        Different vulnerability types need to focus on different response features.
        For example:
        - SQLi: Focus on SQL error messages
        - XSS: Focus on DOM reflection
        - SSRF: Focus on response timing and content
        
        Args:
            payload: The PayloadSpec being tested
            
        Returns:
            Dictionary with hints for LLM analysis
        """
        pass
    
    # === Default Implementations ===
    
    def process_judgment(
        self,
        payload: PayloadSpec,
        result: JudgmentResult,
        raw_request: str,
        raw_response: str,
        target: str,
    ) -> VulnFinding | None:
        """Process LLM judgment result into VulnFinding.
        
        Default implementation converts JudgmentResult to VulnFinding.
        Subclasses can override for custom post-processing.
        
        Args:
            payload: The tested PayloadSpec
            result: LLM's JudgmentResult
            raw_request: Raw HTTP request
            raw_response: Raw HTTP response
            target: Target URL
            
        Returns:
            VulnFinding if confirmed vulnerable, None otherwise
        """
        if not result.is_vulnerable:
            return None
        
        return VulnFinding(
            target=target,
            vuln_type=self.vuln_type,
            payload=payload.payload,
            raw_request=raw_request,
            raw_response=raw_response,
            llm_reasoning=result.reasoning,
            confidence_score=result.confidence_score,
            confidence_level=result.confidence_level,
            risk_level=result.risk_level,
            evidence=result.evidence,
            remediation=result.remediation_advice,
            plugin_name=self.name,
        )
    
    def filter_payloads(
        self,
        payloads: list[PayloadSpec],
        context: PayloadContext,
    ) -> list[PayloadSpec]:
        """Filter payloads based on context.
        
        Default implementation applies max_payloads limit.
        Subclasses can override for smarter filtering (e.g., WAF-aware).
        
        Args:
            payloads: Generated payloads
            context: Current context
            
        Returns:
            Filtered list of payloads
        """
        # Apply max limit
        return payloads[:self.max_payloads]
    
    def get_metadata(self) -> dict[str, Any]:
        """Get plugin metadata."""
        return {
            "name": self.name,
            "vuln_type": self.vuln_type,
            "description": self.description,
            "version": self.version,
            "author": self.author,
            "enabled": self.enabled,
            "max_payloads": self.max_payloads,
        }
